// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALWUflRgVLyqtkUmsSrjKtq4fvHO4g4DI',
    appId: '1:215205414241:web:83a66049f3d99e168c3120',
    messagingSenderId: '215205414241',
    projectId: 'clinic-app-bc9f6',
    authDomain: 'clinic-app-bc9f6.firebaseapp.com',
    storageBucket: 'clinic-app-bc9f6.firebasestorage.app',
    measurementId: 'G-KDE4H5KH22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQjMSzbIzJLLP3DzhOOMR5I24ABkB0j4g',
    appId: '1:215205414241:android:34f669a16011a1678c3120',
    messagingSenderId: '215205414241',
    projectId: 'clinic-app-bc9f6',
    storageBucket: 'clinic-app-bc9f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAbv6zBgpe5bgNBuLrsRi4O6TmF7nqE-8',
    appId: '1:215205414241:ios:55275bccb2dc07ff8c3120',
    messagingSenderId: '215205414241',
    projectId: 'clinic-app-bc9f6',
    storageBucket: 'clinic-app-bc9f6.firebasestorage.app',
    iosBundleId: 'com.example.clinicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAbv6zBgpe5bgNBuLrsRi4O6TmF7nqE-8',
    appId: '1:215205414241:ios:55275bccb2dc07ff8c3120',
    messagingSenderId: '215205414241',
    projectId: 'clinic-app-bc9f6',
    storageBucket: 'clinic-app-bc9f6.firebasestorage.app',
    iosBundleId: 'com.example.clinicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALWUflRgVLyqtkUmsSrjKtq4fvHO4g4DI',
    appId: '1:215205414241:web:a0640a3a601423de8c3120',
    messagingSenderId: '215205414241',
    projectId: 'clinic-app-bc9f6',
    authDomain: 'clinic-app-bc9f6.firebaseapp.com',
    storageBucket: 'clinic-app-bc9f6.firebasestorage.app',
    measurementId: 'G-M1H75L8C0N',
  );
}
